sudo: required
language: java
jdk: oraclejdk8
services:
- docker

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}

git:
  depth: 500

before_install:
- chmod +x mvnw

script:
- "./mvnw clean install -B"

cache:
  directories:
  - "$HOME/.m2/repository"

after_success:
- docker login -u baraneetharan -p Baranee@123
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
- export IMAGE_NAME=baraneetharan/glms
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME

deploy:
  provider: heroku
  api_key: e091f2d5-df18-489b-8da6-db8735cd8df8
  app: glms